import { useEffect, useState } from 'react';
import { CheckCircle2, RefreshCw, Save, ShieldCheck, Target, TrendingDown, WalletCards } from 'lucide-react';
import { smartPurchaseUnifiedApi as api } from '@/api/smartPurchaseUnifiedApi';

const BRANCHES = [['all','كل الفروع'],['دواء الشامي','دواء الشامي'],['دواء شكري','دواء شكري']];
const money = (v) => new Intl.NumberFormat('ar-EG',{maximumFractionDigits:0}).format(Number(v||0));
const num = (v,d=0) => Number(v||0).toFixed(d);

function Card({icon:Icon,label,value,hint}){return <div className="rounded-2xl border bg-white p-3 shadow-sm"><div className="flex gap-2"><div className="rounded-xl bg-emerald-50 p-2"><Icon className="w-4 h-4 text-emerald-700"/></div><div><div className="text-xs text-slate-500">{label}</div><div className="mt-1 text-lg font-black">{value}</div>{hint&&<div className="mt-1 text-[11px] text-slate-400">{hint}</div>}</div></div></div>}

export default function ClearanceOutcomeTracker(){
  const [branch,setBranch]=useState('all'); const [data,setData]=useState(null); const [loading,setLoading]=useState(true); const [message,setMessage]=useState(''); const [error,setError]=useState('');
  async function load(next=branch){setLoading(true);setError('');try{setData(await api.clearanceOutcomes(next));}catch(e){setError(e.message);}finally{setLoading(false);}}
  useEffect(()=>{load(branch);},[branch]);
  async function capture(){setLoading(true);setError('');setMessage('');try{const r=await api.captureClearancePlan(branch);setMessage(`تم حفظ خطة المتابعة: ${r?.tracked_items||0} صنف/Batch. سيتم قياس النتيجة مع كل تحديث لاحق لبيانات المخزون.`);await load(branch);}catch(e){setError(e.message);setLoading(false);}}
  const s=data?.summary||{};
  return <section className="rounded-2xl border border-emerald-200 bg-emerald-50/30 p-4 shadow-sm space-y-4">
    <div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="text-xl font-black flex items-center gap-2"><ShieldCheck className="w-6 h-6 text-emerald-700"/>قياس نتيجة التصريف ورأس المال المُنقذ</h2><p className="mt-1 text-xs text-slate-600">يحفظ خطة التصريف كنقطة أساس، ثم يقارنها بكميات الـBatch المحدثة ويقيس الانخفاض الفعلي في المخزون وقيمة الخطر التي تم تجنبها.</p></div><div className="flex flex-wrap gap-2"><select value={branch} onChange={e=>setBranch(e.target.value)} className="rounded-lg border bg-white p-2 text-sm">{BRANCHES.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select><button onClick={capture} disabled={loading} className="rounded-lg bg-emerald-700 text-white px-3 py-2 text-sm font-bold flex gap-2 items-center"><Save className="w-4 h-4"/>حفظ خطة اليوم للمتابعة</button><button onClick={()=>load()} disabled={loading} className="rounded-lg border bg-white px-3 py-2 text-sm flex gap-2 items-center"><RefreshCw className={`w-4 h-4 ${loading?'animate-spin':''}`}/>تحديث النتيجة</button></div></div>
    {message&&<div className="rounded-xl border border-emerald-200 bg-emerald-50 p-3 text-emerald-800 flex gap-2"><CheckCircle2 className="w-5 h-5"/>{message}</div>}{error&&<div className="rounded-xl border border-red-200 bg-red-50 p-3 text-red-700">{error}</div>}
    <div className="grid grid-cols-2 xl:grid-cols-6 gap-2"><Card icon={Target} label="إجراءات تحت المتابعة" value={num(s.tracked_actions)}/><Card icon={WalletCards} label="قيمة الخطر المخطط" value={`${money(s.planned_risk_value)} ج`}/><Card icon={ShieldCheck} label="رأس مال مُنقذ تقديريًا" value={`${money(s.avoided_loss_value)} ج`} hint="على تكلفة الشراء"/><Card icon={TrendingDown} label="انخفاض مخزون مُلاحظ" value={`${num(s.observed_reduction_units)} وحدة`}/><Card icon={CheckCircle2} label="وحدات خطر تم تجنبها" value={num(s.avoided_risk_units)}/><Card icon={ShieldCheck} label="نسبة نجاح الخطة" value={`${num(s.success_percent,1)}%`}/></div>
    <div className="overflow-auto rounded-xl border bg-white"><table className="min-w-[1200px] w-full text-sm"><thead className="bg-emerald-50"><tr>{['الفرع','الصنف / Batch','تاريخ الخطة','قبل','حاليًا','المطلوب تصريفه','الانخفاض الملحوظ','وحدات خطر تم إنقاذها','قيمة مُنقذة','الإنجاز'].map(h=><th key={h} className="p-2 text-right">{h}</th>)}</tr></thead><tbody>{(data?.items||[]).slice(0,60).map((r,i)=><tr key={`${r.product_name}-${r.batch_number}-${i}`} className="border-t"><td className="p-2">{r.branch}</td><td className="p-2"><div className="font-bold">{r.product_name}</div><div className="text-[11px] text-slate-400">{r.batch_number||'بدون Batch'} • صلاحية {r.expiry_date||'—'}</div></td><td className="p-2 text-xs">{r.generated_at?new Date(r.generated_at).toLocaleDateString('ar-EG'):'—'}</td><td className="p-2">{num(r.starting_quantity)}</td><td className="p-2">{r.current_quantity==null?'—':num(r.current_quantity)}</td><td className="p-2 font-bold">{num(r.units_to_act)}</td><td className="p-2 font-bold text-blue-700">{num(r.observed_reduction)}</td><td className="p-2 font-black text-emerald-700">{num(r.avoided_risk_units)}</td><td className="p-2 font-black text-emerald-800">{money(r.avoided_loss_value)} ج</td><td className="p-2"><div className="w-28 rounded-full bg-slate-100 h-2 overflow-hidden"><div className="h-full bg-emerald-600" style={{width:`${Math.min(100,Number(r.completion_percent||0))}%`}}/></div><div className="text-[11px] mt-1">{num(r.completion_percent,1)}%</div></td></tr>)}{!loading&&!(data?.items||[]).length&&<tr><td colSpan="10" className="p-8 text-center text-slate-400">لا توجد خطة محفوظة بعد. اضغط «حفظ خطة اليوم للمتابعة» لبدء قياس النتيجة.</td></tr>}</tbody></table></div>
    <div className="rounded-xl bg-slate-100 p-3 text-[11px] text-slate-600">«رأس المال المُنقذ» هنا KPI تشغيلي: كمية الخطر التي اختفت من رصيد الـBatch بعد الخطة × تكلفة الشراء. انخفاض الرصيد لا يثبت وحده أنها مبيعات؛ قد يشمل تحويلًا أو مرتجعًا، لذلك لا يُعرض كربح أو مبيعات محاسبية.</div>
  </section>;
}
