import { useEffect, useMemo, useState } from 'react';
import {
  AlertTriangle, Boxes, Gauge, PackageSearch, RefreshCw, TrendingUp, WalletCards,
  ShieldAlert, CircleDollarSign, Clock3, BadgeDollarSign, CalendarClock, Stethoscope,
} from 'lucide-react';
import { smartPurchaseUnifiedApi as api } from '@/api/smartPurchaseUnifiedApi';

const BRANCHES = [['all','كل الفروع'],['دواء الشامي','دواء الشامي'],['دواء شكري','دواء شكري']];
const money = (value) => new Intl.NumberFormat('ar-EG', { maximumFractionDigits: 0 }).format(Number(value || 0));
const num = (value, digits = 1) => Number(value || 0).toFixed(digits);
const TABS = [
  ['cash_locked','فلوس محبوسة'],['deadstock','رواكد'],['slow_movers','بطيئة الحركة'],
  ['high_turnover','عالية الدوران'],['stock_needed','مطلوب استوك'],['profitability','الأكثر ربحية'],
  ['near_expiry','Near Expiry'],['doctor_profit_list','لستة الدكاترة'],
];
function SummaryCard({ icon: Icon, label, value, hint }) { return <div className="rounded-2xl border bg-white p-3 shadow-sm"><div className="flex items-start gap-2"><div className="rounded-xl bg-slate-50 p-2"><Icon className="h-4 w-4 text-teal-700" /></div><div><div className="text-xs text-slate-500">{label}</div><div className="mt-1 text-lg font-black">{value}</div>{hint && <div className="mt-1 text-[11px] text-slate-400">{hint}</div>}</div></div></div>; }

function StandardTable({ type, rows }) {
  if (!rows.length) return <div className="rounded-xl border border-dashed p-7 text-center text-slate-400">لا توجد بيانات في القائمة الحالية.</div>;
  const showNeed=type==='stock_needed', showTurn=type==='high_turnover', showLocked=type==='cash_locked';
  return <div className="overflow-auto rounded-xl border bg-white"><table className="min-w-[980px] w-full text-sm"><thead className="bg-slate-50"><tr><th className="p-2 text-right">الفرع</th><th className="p-2 text-right">الصنف</th><th className="p-2 text-right">الرصيد</th><th className="p-2 text-right">مبيعات 30</th><th className="p-2 text-right">تغطية</th>{showTurn&&<th className="p-2 text-right">معدل يومي</th>}{showNeed&&<><th className="p-2 text-right">كمية الشهر</th><th className="p-2 text-right">تكلفة الاستوك</th></>}{showLocked&&<><th className="p-2 text-right">قيمة المخزون</th><th className="p-2 text-right">قيمة زائدة +45 يوم</th></>}{!showNeed&&!showLocked&&<th className="p-2 text-right">قيمة المخزون</th>}</tr></thead><tbody>{rows.map((r,i)=><tr key={`${r.branch}-${r.product_code||r.product_name}-${i}`} className="border-t hover:bg-slate-50"><td className="p-2 text-xs">{r.branch}</td><td className="p-2"><div className="font-bold">{r.product_name}</div><div className="text-[11px] text-slate-400">{r.product_code||'بدون كود'}</div></td><td className="p-2">{num(r.current_stock,2)}</td><td className="p-2">{num(r.sales_30,2)}</td><td className="p-2">{r.coverage_days==null?'—':`${num(r.coverage_days)} يوم`}</td>{showTurn&&<td className="p-2 font-bold">{num(r.usage_per_day,2)}</td>}{showNeed&&<><td className="p-2 font-black text-teal-800">{num(r.month_need_qty,0)}</td><td className="p-2 font-bold">{money(r.month_need_cost)} ج</td></>}{showLocked&&<><td className="p-2">{money(r.stock_value)} ج</td><td className="p-2 font-bold text-amber-700">{money(r.excess_value_45)} ج</td></>}{!showNeed&&!showLocked&&<td className="p-2">{money(r.stock_value)} ج</td>}</tr>)}</tbody></table></div>;
}
function ProfitTable({ rows }) { if(!rows.length) return <div className="rounded-xl border border-dashed p-7 text-center text-slate-400">ارفع سعر البيع لتفعيل الربحية.</div>; return <div className="overflow-auto rounded-xl border"><table className="min-w-[1050px] w-full text-sm"><thead className="bg-emerald-50"><tr>{['الفرع','الصنف','سعر البيع','تكلفة الشراء','ربح الوحدة','هامش %','مبيعات 30','ربح 30 يوم','GMROI 30'].map(h=><th key={h} className="p-2 text-right">{h}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={i} className="border-t"><td className="p-2">{r.branch}</td><td className="p-2 font-bold">{r.product_name}</td><td className="p-2">{money(r.selling_price)} ج</td><td className="p-2">{money(r.unit_cost)} ج</td><td className="p-2 font-bold text-emerald-700">{money(r.gross_margin_unit)} ج</td><td className="p-2">{num(r.margin_percent)}%</td><td className="p-2">{num(r.sales_30,0)}</td><td className="p-2 font-black text-emerald-800">{money(r.gross_profit_30)} ج</td><td className="p-2 font-bold">{r.gmroi_30==null?'—':num(r.gmroi_30,2)}</td></tr>)}</tbody></table></div>; }
function ExpiryTable({ rows }) { if(!rows.length) return <div className="rounded-xl border border-dashed p-7 text-center text-slate-400">ارفع Batch + Expiry Date + Quantity لتفعيل الرادار.</div>; return <div className="overflow-auto rounded-xl border"><table className="min-w-[1000px] w-full text-sm"><thead className="bg-amber-50"><tr>{['الفرع','الصنف','Batch','الصلاحية','متبقي','الكمية','قيمة مهددة','درجة الخطر'].map(h=><th key={h} className="p-2 text-right">{h}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={i} className="border-t"><td className="p-2">{r.branch}</td><td className="p-2 font-bold">{r.product_name}</td><td className="p-2">{r.batch_number||'—'}</td><td className="p-2">{r.expiry_date}</td><td className={`p-2 font-bold ${Number(r.days_to_expiry)<=30?'text-red-700':Number(r.days_to_expiry)<=60?'text-orange-700':'text-amber-700'}`}>{r.days_to_expiry} يوم</td><td className="p-2">{num(r.expiry_quantity,0)}</td><td className="p-2 font-black">{money(r.expiry_value)} ج</td><td className="p-2">{r.risk_level}</td></tr>)}</tbody></table></div>; }
function DoctorTable({ rows }) { if(!rows.length) return <div className="rounded-xl border border-dashed p-7 text-center text-slate-400">تحتاج سعر بيع موثوق وربحية ورصيد متاح.</div>; return <div className="overflow-auto rounded-xl border"><table className="min-w-[1050px] w-full text-sm"><thead className="bg-blue-50"><tr>{['#','الفرع','الصنف','ربح الوحدة','هامش %','ربح 30 يوم','GMROI','الرصيد','كمية دفع مقترحة','السبب'].map(h=><th key={h} className="p-2 text-right">{h}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={i} className="border-t"><td className="p-2 font-black">{i+1}</td><td className="p-2">{r.branch}</td><td className="p-2 font-bold">{r.product_name}</td><td className="p-2">{money(r.gross_margin_unit)} ج</td><td className="p-2">{num(r.margin_percent)}%</td><td className="p-2 font-black text-blue-800">{money(r.gross_profit_30)} ج</td><td className="p-2">{r.gmroi_30==null?'—':num(r.gmroi_30,2)}</td><td className="p-2">{num(r.current_stock,0)}</td><td className="p-2 font-black">{r.suggested_push_units}</td><td className="p-2 text-xs text-slate-500">{r.reason}</td></tr>)}</tbody></table></div>; }

export default function InventoryCapitalCommandCenter() {
  const [branch,setBranch]=useState('all'); const [data,setData]=useState(null); const [tab,setTab]=useState('cash_locked'); const [loading,setLoading]=useState(true); const [error,setError]=useState('');
  async function load(nextBranch=branch){setLoading(true);setError('');try{setData(await api.inventoryCommandCenter(nextBranch));}catch(e){setError(e.message);}finally{setLoading(false);}}
  useEffect(()=>{load(branch);},[branch]);
  const summary=useMemo(()=>{const rows=data?.summary||[]; const valid=rows.filter(x=>x.capital_cycle_days!=null); return {stock:rows.reduce((s,x)=>s+Number(x.total_stock_value||0),0),locked:rows.reduce((s,x)=>s+Number(x.locked_over_45_value||0),0),dead:rows.reduce((s,x)=>s+Number(x.deadstock_value||0),0),need:rows.reduce((s,x)=>s+Number(x.month_need_cost||0),0),velocity:rows.reduce((s,x)=>s+Number(x.daily_cost_velocity||0),0),cycleDays:valid.length?valid.reduce((s,x)=>s+Number(x.capital_cycle_days||0),0)/valid.length:0};},[data]);
  const activeRows=data?.[tab]||[];
  return <section className="rounded-2xl border border-slate-200 bg-slate-50/50 p-4 shadow-sm space-y-4">
    <div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="text-xl font-black flex items-center gap-2"><CircleDollarSign className="w-6 h-6 text-teal-700" />مركز ذكاء المخزون ورأس المال</h2><p className="text-xs text-slate-500 mt-1">السيولة، الدوران، الربحية، الصلاحية، والاستوك المقترح من مكان واحد.</p></div><div className="flex gap-2"><select value={branch} onChange={e=>setBranch(e.target.value)} className="rounded-lg border bg-white p-2 text-sm">{BRANCHES.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select><button onClick={()=>load()} disabled={loading} className="rounded-lg border bg-white px-3 py-2 text-sm flex items-center gap-2"><RefreshCw className={`w-4 h-4 ${loading?'animate-spin':''}`} />تحديث</button></div></div>
    {error&&<div className="rounded-xl border border-red-200 bg-red-50 p-3 text-red-700 flex gap-2"><AlertTriangle className="w-5 h-5" />{error}</div>}
    <div className="grid grid-cols-2 xl:grid-cols-6 gap-2"><SummaryCard icon={Boxes} label="قيمة المخزون المحلل" value={`${money(summary.stock)} ج`} /><SummaryCard icon={WalletCards} label="سيولة زائدة فوق 45 يوم" value={`${money(summary.locked)} ج`} /><SummaryCard icon={ShieldAlert} label="قيمة الرواكد" value={`${money(summary.dead)} ج`} /><SummaryCard icon={PackageSearch} label="تكلفة استوك 30 يوم الخام" value={`${money(summary.need)} ج`} hint="ليست توصية تلقائية لكل صنف غالي" /><SummaryCard icon={TrendingUp} label="سرعة خروج تكلفة/يوم" value={`${money(summary.velocity)} ج`} /><SummaryCard icon={Clock3} label="دورة رأس المال الحالية" value={summary.cycleDays?`${num(summary.cycleDays)} يوم`:'—'} /></div>
    <div className="grid md:grid-cols-3 gap-2">{(data?.investment_scenarios||[]).map(r=><div key={r.investment} className="rounded-2xl border bg-white p-3"><div className="text-xs text-slate-500">لو استثمرنا {money(r.investment)} ج زيادة</div><div className="mt-1 font-black">متاح توزيعه: {money(r.allocatable_value)} ج</div><div className="mt-1 text-sm">{r.selected_items} صنف • دوران {r.estimated_days_to_cycle==null?'غير كافٍ':`${num(r.estimated_days_to_cycle)} يوم`}</div></div>)}</div>
    <div className="rounded-2xl border bg-white p-3"><div className="flex flex-wrap gap-2">{TABS.map(([v,l])=><button key={v} onClick={()=>setTab(v)} className={`rounded-lg px-3 py-2 text-sm font-bold ${tab===v?'bg-slate-900 text-white':'border bg-white'}`}>{l} <span className="opacity-60">({(data?.[v]||[]).length})</span></button>)}</div><div className="mt-3">{tab==='profitability'?<ProfitTable rows={activeRows}/>:tab==='near_expiry'?<ExpiryTable rows={activeRows}/>:tab==='doctor_profit_list'?<DoctorTable rows={activeRows}/>:<StandardTable type={tab} rows={activeRows}/>}</div></div>
    <div className="grid md:grid-cols-3 gap-2"><div className={`rounded-xl border p-3 ${data?.readiness?.profitability_ready?'bg-emerald-50 border-emerald-200':'bg-amber-50 border-amber-200'}`}><div className="font-bold text-sm flex gap-2"><BadgeDollarSign className="w-4 h-4"/>الربحية وGMROI</div><div className="text-xs mt-1">{data?.readiness?.profitability_reason}</div></div><div className={`rounded-xl border p-3 ${data?.readiness?.expiry_ready?'bg-emerald-50 border-emerald-200':'bg-amber-50 border-amber-200'}`}><div className="font-bold text-sm flex gap-2"><CalendarClock className="w-4 h-4"/>Near Expiry Radar</div><div className="text-xs mt-1">{data?.readiness?.expiry_reason}</div></div><div className={`rounded-xl border p-3 ${data?.readiness?.doctor_profit_list_ready?'bg-emerald-50 border-emerald-200':'bg-blue-50 border-blue-200'}`}><div className="font-bold text-sm flex gap-2"><Stethoscope className="w-4 h-4"/>لستة الدكاترة</div><div className="text-xs mt-1">{data?.readiness?.doctor_profit_list_reason}</div></div></div>
    <div className="rounded-xl bg-slate-100 p-3 text-[11px] text-slate-600 flex gap-2"><Gauge className="w-4 h-4 shrink-0" />GMROI هنا تشغيلي على الربح الإجمالي المقدّر ومخزون التكلفة، وليس صافي ربح محاسبي بعد المصروفات.</div>
  </section>;
}
