import {useEffect,useMemo,useState} from 'react';
import * as XLSX from 'xlsx';
import {smartPurchaseUnifiedApi as unified} from '@/api/smartPurchaseUnifiedApi';
import {smartPurchaseOrderManagementApi as management} from '@/api/smartPurchaseOrderManagementApi';
import {smartPurchaseApi} from '@/api/smartPurchaseApi';
import {AlertTriangle,CheckCircle2,Download,FileSpreadsheet,RefreshCw,Send,Sparkles,Upload,ShoppingCart,SlidersHorizontal,Save} from 'lucide-react';

const money=v=>new Intl.NumberFormat('ar-EG',{maximumFractionDigits:2}).format(Number(v||0));
const STATUS_STEPS=['مسودة','تم التحليل','معتمدة','تم الإرسال للمورد','وصلت جزئيًا','وصلت بالكامل','تمت مطابقة الفاتورة','مغلقة'];
const normStatus=s=>s==='draft'?'مسودة':s||'مسودة';
const MAPPING_KEY='dawaa_purchase_excel_mappings_v1';
const FIELD_LABELS={product_code:'كود الصنف',product_name:'اسم الصنف',current_stock:'الرصيد الحالي',sales_30:'مبيعات 30 يوم',sales_60:'مبيعات 60 يوم',sales_90:'مبيعات 90 يوم',avg_daily_usage:'متوسط الاستهلاك اليومي',old_discount:'الخصم السابق',last_purchase_price:'آخر سعر شراء',preferred_supplier:'المورد',pending_incoming:'الكمية المنتظر وصولها'};
const aliases={
  product_code:['كود الصنف','كود','code','item code','product code','itemcode'],
  product_name:['اسم الصنف','الصنف','name','item name','product name','description','item','اسم المنتج'],
  current_stock:['الرصيد الحالي','الرصيد','stock','current stock','balance','qty balance'],
  sales_30:['مبيعات 30 يوم','مبيعات 30','sales 30','sales_30','qty sold','sales qty'],
  sales_60:['مبيعات 60 يوم','مبيعات 60','sales 60','sales_60'],
  sales_90:['مبيعات 90 يوم','مبيعات 90','sales 90','sales_90'],
  avg_daily_usage:['متوسط الاستهلاك اليومي','متوسط الاستهلاك','avg daily usage','daily average','daily usage'],
  old_discount:['الخصم السابق','نسبة الخصم','discount','old discount'],
  last_purchase_price:['آخر سعر شراء','سعر الشراء','purchase price','last purchase price','cost'],
  preferred_supplier:['المورد','المورد السابق','supplier','preferred supplier','vendor'],
  pending_incoming:['كمية منتظر وصولها','منتظر وصول','pending incoming','incoming qty','on order'],
};
const norm=v=>String(v??'').trim().toLowerCase().replace(/[\s_\-]+/g,' ');
const num=v=>{const n=Number(String(v??'').replace(/[,٪%جنيه]/g,'').trim());return Number.isFinite(n)?n:0;};
function autoMapping(headers){const out={};Object.keys(FIELD_LABELS).forEach(field=>{out[field]=headers.find(h=>(aliases[field]||[]).some(a=>norm(h)===norm(a)))||headers.find(h=>(aliases[field]||[]).some(a=>norm(h).includes(norm(a))||norm(a).includes(norm(h))))||'';});return out;}
function signature(headers){return headers.map(norm).sort().join('|');}
function loadMappings(){try{return JSON.parse(localStorage.getItem(MAPPING_KEY)||'{}');}catch{return {};}}
function workbookBySupplier(order){
  const groups={};
  (order.items||[]).filter(x=>Number(x.approved_quantity||0)>0).forEach(x=>{const supplier=x.supplier_name||'بدون مورد';(groups[supplier]??=[]).push({'كود الصنف':x.product_code||'','اسم الصنف':x.product_name,'الكمية':Number(x.approved_quantity||0),'سعر الوحدة المتوقع':Number(x.expected_unit_cost||0),'الإجمالي':Number(x.approved_quantity||0)*Number(x.expected_unit_cost||0),'ملاحظات':x.notes||''});});
  const wb=XLSX.utils.book_new();Object.entries(groups).forEach(([name,rows])=>{const ws=XLSX.utils.json_to_sheet(rows);ws['!dir']='rtl';ws['!cols']=[14,34,12,18,18,28].map(wch=>({wch}));XLSX.utils.book_append_sheet(wb,ws,name.slice(0,31));});XLSX.writeFile(wb,`${order.order.order_number}_حسب_المورد.xlsx`);
}

export default function SmartPurchaseUnifiedCenter(){
  const [data,setData]=useState({orders:[],treasuries:[],pending_actions:{}});const [selected,setSelected]=useState(null);
  const [loading,setLoading]=useState(false);const [error,setError]=useState('');const [message,setMessage]=useState('');
  const [showImport,setShowImport]=useState(false);const [branch,setBranch]=useState('دواء الشامي');const [coverageDays,setCoverageDays]=useState(21);const [safetyDays,setSafetyDays]=useState(5);const [fileName,setFileName]=useState('');const [preview,setPreview]=useState([]);const [previewErrors,setPreviewErrors]=useState([]);
  const [rawRows,setRawRows]=useState([]);const [headers,setHeaders]=useState([]);const [mapping,setMapping]=useState({});const [mappingSource,setMappingSource]=useState('');
  const [bulkSupplier,setBulkSupplier]=useState('');const [bulkPercent,setBulkPercent]=useState(100);const [onlyUrgent,setOnlyUrgent]=useState(false);const [onlyCustomers,setOnlyCustomers]=useState(false);const [hideZero,setHideZero]=useState(true);

  async function refresh(openId){setLoading(true);setError('');try{const d=await unified.dashboard();setData(d||{orders:[],treasuries:[],pending_actions:{}});const id=openId||selected?.order?.id;if(id)setSelected(await unified.getOrder(id));}catch(e){setError(e.message);}finally{setLoading(false);}}
  useEffect(()=>{refresh();},[]);
  async function openOrder(id){setLoading(true);setError('');setMessage('');try{setSelected(await unified.getOrder(id));}catch(e){setError(e.message);}finally{setLoading(false);}}
  async function run(fn,msg,openId){setLoading(true);setError('');setMessage('');try{const result=await fn();setMessage(msg);await refresh(openId||result?.id);}catch(e){setError(e.message);}finally{setLoading(false);}}
  async function optimize(){if(selected)await run(()=>management.optimizeSuppliers(selected.order.id),'تم اختيار أفضل مورد متاح لكل صنف.');}
  async function approve(){if(selected)await run(()=>unified.approveOrder(selected.order.id),'تم اعتماد الطلبية بنجاح.');}
  async function returnToReview(){if(selected)await run(()=>unified.returnToReview(selected.order.id),'تمت إعادة الطلبية للمراجعة.');}
  async function markSent(){if(selected)await run(()=>unified.markSent(selected.order.id),'تم تسجيل إرسال الطلبية للموردين.');}

  function buildPreview(rows,nextMapping){
    const parsed=rows.map((r,index)=>({row_number:index+2,product_code:String(r[nextMapping.product_code]??'').trim(),product_name:String(r[nextMapping.product_name]??'').trim(),current_stock:num(r[nextMapping.current_stock]),sales_30:num(r[nextMapping.sales_30]),sales_60:num(r[nextMapping.sales_60]),sales_90:num(r[nextMapping.sales_90]),avg_daily_usage:num(r[nextMapping.avg_daily_usage]),old_discount:num(r[nextMapping.old_discount]),last_purchase_price:num(r[nextMapping.last_purchase_price]),preferred_supplier:String(r[nextMapping.preferred_supplier]??'').trim(),pending_incoming:num(r[nextMapping.pending_incoming])}));
    const errors=[];parsed.forEach(r=>{if(!r.product_name)errors.push(`صف ${r.row_number}: اسم الصنف غير موجود`);if(r.current_stock<0)errors.push(`صف ${r.row_number}: الرصيد الحالي سالب`);});
    const merged=new Map();parsed.filter(r=>r.product_name).forEach(r=>{const key=r.product_code||norm(r.product_name);if(merged.has(key)){const old=merged.get(key);merged.set(key,{...old,current_stock:Math.max(old.current_stock,r.current_stock),sales_30:old.sales_30+r.sales_30,sales_60:old.sales_60+r.sales_60,sales_90:old.sales_90+r.sales_90,pending_incoming:old.pending_incoming+r.pending_incoming});}else merged.set(key,r);});
    setPreview([...merged.values()]);setPreviewErrors(errors);
    return {rows:parsed.length,valid:merged.size,errors:errors.length};
  }
  async function readFile(file){
    setError('');setMessage('');setFileName(file.name);
    try{
      const wb=XLSX.read(await file.arrayBuffer(),{type:'array'});const rows=XLSX.utils.sheet_to_json(wb.Sheets[wb.SheetNames[0]],{defval:''});const cols=Object.keys(rows[0]||{});
      if(!rows.length||!cols.length)throw new Error('الملف فارغ أو لا يحتوي على عناوين أعمدة.');
      const saved=loadMappings()[signature(cols)];const next=saved||autoMapping(cols);setRawRows(rows);setHeaders(cols);setMapping(next);setMappingSource(saved?'تم تطبيق قالب محفوظ تلقائيًا':'تم التعرف على الأعمدة تلقائيًا');
      const stats=buildPreview(rows,next);setMessage(`تمت قراءة ${stats.rows} صف وتجميعها إلى ${stats.valid} صنف صالح. ${saved?'تم استخدام قالب الأعمدة المحفوظ.':'راجع ربط الأعمدة قبل الإنشاء.'}`);
    }catch(e){setError(`تعذر قراءة الملف: ${e.message}`);setPreview([]);setRawRows([]);setHeaders([]);}
  }
  function changeMapping(field,value){const next={...mapping,[field]:value};setMapping(next);buildPreview(rawRows,next);setMappingSource('تم تعديل ربط الأعمدة يدويًا — احفظ القالب لاستخدامه لاحقًا');}
  function saveMapping(){if(!headers.length)return;const all=loadMappings();all[signature(headers)]=mapping;localStorage.setItem(MAPPING_KEY,JSON.stringify(all));setMappingSource('تم حفظ قالب الأعمدة على هذا الجهاز');setMessage('تم حفظ قالب الأعمدة، وسيتم تطبيقه تلقائيًا على الملفات بنفس العناوين.');}
  async function importAndCreate(){
    if(!mapping.product_name)return setError('حدد عمود اسم الصنف أولًا.');
    if(!preview.length)return setError('ارفع ملف Excel صالح أولًا.');
    await run(async()=>{const imported=await smartPurchaseApi.importRows({file_name:fileName,branch,coverage_days:coverageDays,safety_days:safetyDays,rows:preview});const created=await smartPurchaseApi.createOrder({import_id:imported.id,branch,title:`طلبية ${branch}`});setPreview([]);setPreviewErrors([]);setFileName('');setShowImport(false);setRawRows([]);setHeaders([]);return created;},'تم تحليل الملف وإنشاء الطلبية وفتحها للمراجعة.');
  }

  async function updateOne(item,patch){await management.updateItem({id:item.id,order_id:selected.order.id,...patch});}
  async function applyBulkQuantity(){if(!selected)return;const pct=Math.max(0,Number(bulkPercent||0))/100;const rows=visibleItems;setLoading(true);setError('');try{for(const item of rows){await updateOne(item,{approved_quantity:Math.max(0,Math.round(Number(item.requested_quantity||item.approved_quantity||0)*pct))});}setMessage(`تم تحديث كميات ${rows.length} صنف بنسبة ${bulkPercent}%.`);await refresh();}catch(e){setError(e.message);}finally{setLoading(false);}}
  async function applyBulkSupplier(){if(!selected||!bulkSupplier.trim())return setError('اكتب اسم المورد أولًا.');const rows=visibleItems.filter(x=>Number(x.approved_quantity||0)>0);setLoading(true);setError('');try{for(const item of rows){await updateOne(item,{supplier_name:bulkSupplier.trim()});}setMessage(`تم تعيين المورد «${bulkSupplier.trim()}» إلى ${rows.length} صنف.`);await refresh();}catch(e){setError(e.message);}finally{setLoading(false);}}
  async function zeroVisible(){if(!selected)return;setLoading(true);setError('');try{for(const item of visibleItems){await updateOne(item,{approved_quantity:0});}setMessage(`تم تصفير ${visibleItems.length} صنف ظاهر.`);await refresh();}catch(e){setError(e.message);}finally{setLoading(false);}}

  const importWarnings=useMemo(()=>({zeroPrice:preview.filter(x=>Number(x.last_purchase_price||0)<=0).length,noSupplier:preview.filter(x=>!x.preferred_supplier).length,noCode:preview.filter(x=>!x.product_code).length,noDemand:!mapping.sales_30&&!mapping.avg_daily_usage}),[preview,mapping]);
  const totals=useMemo(()=>{const items=selected?.items||[];return{items:items.length,suppliers:new Set(items.map(x=>x.supplier_name).filter(Boolean)).size,missing:items.filter(x=>Number(x.approved_quantity||0)>0&&!x.supplier_name).length,total:items.reduce((s,x)=>s+Number(x.approved_quantity||0)*Number(x.expected_unit_cost||0),0),customers:items.reduce((s,x)=>s+Number(x.customer_requests_count||0),0)};},[selected]);
  const visibleItems=useMemo(()=>{let rows=selected?.items||[];if(hideZero)rows=rows.filter(x=>Number(x.approved_quantity||0)>0);if(onlyUrgent)rows=rows.filter(x=>Number(x.priority_score||0)>=50||String(x.priority_label||'').includes('عاجل'));if(onlyCustomers)rows=rows.filter(x=>Number(x.customer_requests_count||0)>0);return rows;},[selected,hideZero,onlyUrgent,onlyCustomers]);
  const status=normStatus(selected?.order?.status);const stepIndex=Math.max(0,STATUS_STEPS.indexOf(status));

  return <div dir="rtl" className="p-4 md:p-6 space-y-5">
    <div className="flex flex-wrap items-start justify-between gap-3"><div><h1 className="text-2xl font-bold">مركز الطلبية السريع</h1><p className="text-sm text-slate-500 mt-1">ارفع الملف، راجع الكميات والموردين، اعتمد وصدّر من شاشة واحدة.</p></div><div className="flex gap-2"><button onClick={()=>setShowImport(v=>!v)} className="rounded-lg bg-emerald-600 text-white px-4 py-2 flex gap-2"><Upload className="w-4 h-4"/>طلبية جديدة من Excel</button><button onClick={()=>refresh()} className="rounded-lg border bg-white px-4 py-2 flex gap-2"><RefreshCw className="w-4 h-4"/>تحديث</button></div></div>
    {error&&<div className="rounded-xl border border-red-200 bg-red-50 p-3 text-red-700 flex gap-2"><AlertTriangle className="w-5 h-5"/>{error}</div>}{message&&<div className="rounded-xl border border-emerald-200 bg-emerald-50 p-3 text-emerald-700">{message}</div>}

    {showImport&&<section className="rounded-2xl border border-emerald-200 bg-white p-4 shadow-sm space-y-4">
      <div className="flex items-center gap-2"><FileSpreadsheet className="w-5 h-5 text-emerald-600"/><h2 className="font-bold">إنشاء طلبية جديدة من Excel</h2></div>
      <div className="grid md:grid-cols-4 gap-3"><label className="text-sm">الفرع<select value={branch} onChange={e=>setBranch(e.target.value)} className="mt-1 w-full rounded-lg border p-2"><option>دواء الشامي</option><option>دواء شكري</option></select></label><label className="text-sm">أيام التغطية<input type="number" min="1" value={coverageDays} onChange={e=>setCoverageDays(Number(e.target.value))} className="mt-1 w-full rounded-lg border p-2"/></label><label className="text-sm">أيام مخزون الأمان<input type="number" min="0" value={safetyDays} onChange={e=>setSafetyDays(Number(e.target.value))} className="mt-1 w-full rounded-lg border p-2"/></label><label className="text-sm">ملف Excel<input type="file" accept=".xlsx,.xls,.csv" onChange={e=>e.target.files?.[0]&&readFile(e.target.files[0])} className="mt-1 block w-full text-sm"/></label></div>
      {headers.length>0&&<div className="rounded-xl border border-blue-200 bg-blue-50 p-3 space-y-3"><div className="flex flex-wrap items-center justify-between gap-2"><div><h3 className="font-bold text-blue-900">ربط أعمدة الملف</h3><p className="text-xs text-blue-700">{mappingSource}</p></div><button onClick={saveMapping} className="rounded-lg bg-white border border-blue-200 px-3 py-2 text-sm font-semibold flex gap-2"><Save className="w-4 h-4"/>حفظ القالب</button></div><div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-2">{Object.entries(FIELD_LABELS).map(([field,label])=><label key={field} className="text-xs font-semibold text-slate-600">{label}{field==='product_name'&&<span className="text-red-600"> *</span>}<select value={mapping[field]||''} onChange={e=>changeMapping(field,e.target.value)} className="mt-1 w-full rounded-lg border bg-white p-2 text-sm"><option value="">غير موجود</option>{headers.map(h=><option key={h} value={h}>{h}</option>)}</select></label>)}</div></div>}
      {preview.length>0&&<><div className="grid sm:grid-cols-4 gap-2">{[['الملف',fileName],['الأصناف الصالحة',preview.length],['ملاحظات الصفوف',previewErrors.length],['الفرع',branch]].map(([l,v])=><div key={l} className="rounded-xl bg-slate-50 p-3"><div className="text-xs text-slate-500">{l}</div><div className="font-bold mt-1 truncate">{v}</div></div>)}</div>
      {(importWarnings.zeroPrice||importWarnings.noSupplier||importWarnings.noCode||importWarnings.noDemand)&&<div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-2">{importWarnings.noDemand&&<div className="rounded-xl border border-red-200 bg-red-50 p-3 text-sm text-red-700">لا يوجد عمود مبيعات 30 يوم أو متوسط استهلاك؛ التحليل لن يكون دقيقًا.</div>}{importWarnings.zeroPrice>0&&<div className="rounded-xl border border-amber-200 bg-amber-50 p-3 text-sm text-amber-800">{importWarnings.zeroPrice} صنف بدون سعر شراء، ويمكن تحديد السعر لاحقًا.</div>}{importWarnings.noSupplier>0&&<div className="rounded-xl border border-amber-200 bg-amber-50 p-3 text-sm text-amber-800">{importWarnings.noSupplier} صنف بدون مورد.</div>}{importWarnings.noCode>0&&<div className="rounded-xl border border-slate-200 bg-slate-50 p-3 text-sm text-slate-700">{importWarnings.noCode} صنف بدون كود؛ سيتم الاعتماد على الاسم.</div>}</div>}
      {previewErrors.length>0&&<details className="rounded-xl border border-amber-200 bg-amber-50 p-3"><summary className="cursor-pointer font-semibold text-amber-800">عرض ملاحظات الملف ({previewErrors.length})</summary><div className="mt-2 max-h-36 overflow-auto text-sm text-amber-800 space-y-1">{previewErrors.slice(0,50).map((x,i)=><div key={i}>{x}</div>)}</div></details>}
      <div className="overflow-auto rounded-xl border"><table className="min-w-[850px] w-full text-sm"><thead className="bg-slate-50"><tr>{['الكود','الصنف','الرصيد','مبيعات 30','متوسط يومي','السعر','المورد'].map(h=><th key={h} className="p-2 text-right">{h}</th>)}</tr></thead><tbody>{preview.slice(0,20).map((x,i)=><tr key={`${x.product_code}-${i}`} className="border-t"><td className="p-2">{x.product_code||'—'}</td><td className="p-2 font-semibold">{x.product_name}</td><td className="p-2">{x.current_stock}</td><td className="p-2">{x.sales_30}</td><td className="p-2">{x.avg_daily_usage}</td><td className="p-2">{money(x.last_purchase_price)}</td><td className="p-2">{x.preferred_supplier||'—'}</td></tr>)}</tbody></table></div>
      <button disabled={loading||!mapping.product_name||importWarnings.noDemand} onClick={importAndCreate} className="rounded-lg bg-emerald-600 px-5 py-2.5 text-white font-bold flex items-center gap-2 disabled:opacity-50"><ShoppingCart className="w-4 h-4"/>تحليل وإنشاء الطلبية</button></>}
    </section>}

    <div className="grid md:grid-cols-3 gap-3">{[['مسودات تحتاج مراجعة',data.pending_actions?.draft||0],['طلبيات بها أصناف بدون مورد',data.pending_actions?.needs_supplier||0],['طلبيات تنتظر الاستلام',data.pending_actions?.pending_receiving||0]].map(([l,v])=><div key={l} className="rounded-2xl border bg-white p-4 shadow-sm"><div className="text-xs text-slate-500">{l}</div><div className="text-2xl font-bold mt-2">{v}</div></div>)}</div>
    <div className="grid lg:grid-cols-[310px_1fr] gap-4">
      <aside className="rounded-2xl border bg-white p-3 shadow-sm h-fit"><h2 className="font-bold mb-3">الطلبيات</h2><div className="space-y-2 max-h-[700px] overflow-auto">{(data.orders||[]).map(o=><button key={o.id} onClick={()=>openOrder(o.id)} className={`w-full text-right rounded-xl border p-3 hover:bg-emerald-50 ${selected?.order?.id===o.id?'border-emerald-500 bg-emerald-50':''}`}><div className="font-semibold">{o.order_number}</div><div className="text-xs text-slate-500 mt-1">{o.branch} • {normStatus(o.status)}</div><div className="font-bold mt-1">{money(o.approved_total||o.expected_total)} ج</div></button>)}{!data.orders?.length&&<p className="text-sm text-slate-400 p-3">لا توجد طلبيات بعد.</p>}</div></aside>
      <main className="space-y-4">{selected?<>
        <section className="rounded-2xl border bg-white p-4 shadow-sm"><div className="flex flex-wrap justify-between gap-3"><div><h2 className="text-xl font-bold">{selected.order.order_number}</h2><p className="text-sm text-slate-500">{selected.order.branch} • {status}</p></div><div className="flex gap-2"><button onClick={()=>workbookBySupplier(selected)} className="rounded-lg border px-3 py-2 flex gap-2"><Download className="w-4 h-4"/>Excel حسب المورد</button>{status==='معتمدة'&&<button onClick={markSent} disabled={loading} className="rounded-lg bg-blue-600 text-white px-3 py-2 flex gap-2"><Send className="w-4 h-4"/>تم الإرسال</button>}</div></div><div className="mt-4 flex overflow-x-auto">{STATUS_STEPS.map((s,i)=><div key={s} className="min-w-[125px] flex-1"><div className={`h-2 ${i<=stepIndex?'bg-emerald-500':'bg-slate-200'}`}/><div className={`text-[11px] mt-2 ${i<=stepIndex?'font-bold text-emerald-700':'text-slate-400'}`}>{s}</div></div>)}</div></section>
        <div className="grid sm:grid-cols-2 xl:grid-cols-5 gap-3">{[['الأصناف',totals.items],['الموردون',totals.suppliers],['بدون مورد',totals.missing],['طلبات العملاء',totals.customers],['إجمالي الطلبية',`${money(totals.total)} ج`]].map(([l,v])=><div key={l} className="rounded-2xl border bg-white p-4 shadow-sm"><div className="text-xs text-slate-500">{l}</div><div className="text-xl font-bold mt-2">{v}</div></div>)}</div>
        <section className="rounded-2xl border bg-white p-4 shadow-sm space-y-3"><div className="flex items-center gap-2"><SlidersHorizontal className="w-5 h-5 text-violet-600"/><h3 className="font-bold">تعديل جماعي سريع</h3><span className="text-xs text-slate-400">يُطبق على الأصناف الظاهرة فقط ({visibleItems.length})</span></div><div className="flex flex-wrap gap-2 items-end"><label className="text-xs">نسبة الكمية<input type="number" min="0" value={bulkPercent} onChange={e=>setBulkPercent(e.target.value)} className="mt-1 w-28 rounded-lg border p-2"/></label><button onClick={applyBulkQuantity} disabled={loading} className="rounded-lg border px-3 py-2 font-semibold">تطبيق النسبة</button><label className="text-xs">تعيين مورد<input value={bulkSupplier} onChange={e=>setBulkSupplier(e.target.value)} placeholder="اسم المورد" className="mt-1 w-44 rounded-lg border p-2"/></label><button onClick={applyBulkSupplier} disabled={loading} className="rounded-lg border px-3 py-2 font-semibold">تعيين للظاهر</button><button onClick={zeroVisible} disabled={loading} className="rounded-lg border border-red-200 text-red-700 px-3 py-2 font-semibold">تصفير الظاهر</button></div><div className="flex flex-wrap gap-4 text-sm"><label className="flex gap-2"><input type="checkbox" checked={hideZero} onChange={e=>setHideZero(e.target.checked)}/>إخفاء الكمية صفر</label><label className="flex gap-2"><input type="checkbox" checked={onlyUrgent} onChange={e=>setOnlyUrgent(e.target.checked)}/>العاجل فقط</label><label className="flex gap-2"><input type="checkbox" checked={onlyCustomers} onChange={e=>setOnlyCustomers(e.target.checked)}/>طلبات العملاء فقط</label></div></section>
        <div className="flex flex-wrap gap-2"><button onClick={optimize} disabled={loading||['معتمدة','تم الإرسال للمورد'].includes(status)} className="rounded-lg bg-violet-600 text-white px-4 py-2 font-semibold flex gap-2"><Sparkles className="w-4 h-4"/>اختيار أفضل الموردين</button>{!['معتمدة','تم الإرسال للمورد'].includes(status)&&<button onClick={approve} disabled={loading||totals.missing>0||totals.total<=0} className="rounded-lg bg-emerald-600 text-white px-4 py-2 font-semibold flex gap-2"><CheckCircle2 className="w-4 h-4"/>اعتماد الطلبية</button>}{['معتمدة','تم الإرسال للمورد'].includes(status)&&<button onClick={returnToReview} disabled={loading} className="rounded-lg border border-amber-300 text-amber-800 px-4 py-2 font-semibold">إعادة للمراجعة</button>}</div>
        <section className="rounded-2xl border bg-white shadow-sm overflow-auto"><table className="min-w-[1100px] w-full text-sm"><thead className="bg-slate-50"><tr>{['الصنف','المطلوب','المعتمد','المورد','سعر الوحدة','الإجمالي','الأولوية','طلبات العملاء'].map(h=><th key={h} className="p-3 text-right">{h}</th>)}</tr></thead><tbody>{visibleItems.map(x=><tr key={x.id} className="border-t"><td className="p-3"><div className="font-semibold">{x.product_name}</div><div className="text-xs text-slate-400">{x.product_code||'بدون كود'}</div></td><td className="p-3">{x.requested_quantity}</td><td className="p-3"><input type="number" min="0" defaultValue={x.approved_quantity} disabled={['معتمدة','تم الإرسال للمورد'].includes(status)} onBlur={e=>{const v=Number(e.target.value);if(v!==Number(x.approved_quantity))run(()=>updateOne(x,{approved_quantity:v}),'تم تحديث كمية الصنف.');}} className="w-24 rounded-lg border p-2 font-bold"/></td><td className="p-3"><input defaultValue={x.supplier_name||''} disabled={['معتمدة','تم الإرسال للمورد'].includes(status)} onBlur={e=>{const v=e.target.value.trim();if(v!==(x.supplier_name||''))run(()=>updateOne(x,{supplier_name:v}),'تم تحديث مورد الصنف.');}} placeholder="حدد المورد" className="w-40 rounded-lg border p-2"/></td><td className="p-3"><input type="number" min="0" step="0.01" defaultValue={x.expected_unit_cost} disabled={['معتمدة','تم الإرسال للمورد'].includes(status)} onBlur={e=>{const v=Number(e.target.value);if(v!==Number(x.expected_unit_cost))run(()=>updateOne(x,{expected_unit_cost:v}),'تم تحديث سعر الصنف.');}} className="w-28 rounded-lg border p-2"/></td><td className="p-3 font-bold">{money(Number(x.approved_quantity||0)*Number(x.expected_unit_cost||0))}</td><td className="p-3">{x.priority_label||x.priority_score}</td><td className="p-3">{x.customer_requests_count||0}</td></tr>)}{!visibleItems.length&&<tr><td colSpan="8" className="p-10 text-center text-slate-400">لا توجد أصناف مطابقة للفلاتر الحالية.</td></tr>}</tbody></table></section>
      </>:<section className="rounded-2xl border border-dashed bg-white p-12 text-center text-slate-400"><FileSpreadsheet className="w-10 h-10 mx-auto mb-3"/>اختر طلبية أو ارفع ملف Excel لبدء العمل.</section>}</main>
    </div>
  </div>;
}
