import { useEffect, useMemo, useState } from 'react';
import * as XLSX from 'xlsx';
import { Download, FileSpreadsheet, Save, Sparkles, CheckCircle2, AlertTriangle, ClipboardCheck, ShieldCheck, Scissors, Trash2 } from 'lucide-react';
import { smartPurchaseOrderManagementApi as api } from '@/api/smartPurchaseOrderManagementApi';

const aliases={product_code:['كود الصنف','كود','product code','item code'],product_name:['اسم الصنف','الصنف','product name','item name'],supplier_name:['اسم المورد','المورد','supplier'],list_price:['السعر قبل الخصم','السعر','list price'],discount_percent:['الخصم %','نسبة الخصم','discount'],extra_discount_percent:['خصم اضافي %','الخصم الاضافي','extra discount'],bonus_quantity:['كمية البونص','البونص','bonus quantity'],bonus_base_quantity:['كمية اساس البونص','البونص لكل','bonus base quantity'],available_quantity:['الكمية المتاحة','متاح','available quantity'],minimum_order_quantity:['اقل كمية طلب','الحد الادنى','minimum order quantity'],lead_time_days:['مدة التوريد','ايام التوريد','lead time'],payment_type:['طريقة الدفع','الدفع','payment type'],valid_until:['ساري حتى','تاريخ انتهاء العرض','valid until']};
const norm=v=>String(v??'').trim().toLowerCase().replace(/\s+/g,' '); const num=v=>{const n=Number(String(v??'').replace(/[,٪%جنيه]/g,'').trim());return Number.isFinite(n)?n:0;};
function get(row,key){const found=Object.keys(row).find(k=>(aliases[key]||[key]).some(a=>norm(a)===norm(k)));return found?row[found]:'';} function money(v){return new Intl.NumberFormat('ar-EG',{maximumFractionDigits:2}).format(Number(v||0));}
function downloadWorkbook(sheets,name){const wb=XLSX.utils.book_new();Object.entries(sheets).forEach(([sheet,rows])=>XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(rows),sheet.slice(0,31)));XLSX.writeFile(wb,name);}

export default function SmartPurchaseOrderManagement(){
 const [orders,setOrders]=useState([]),[selected,setSelected]=useState(null),[offersPreview,setOffersPreview]=useState([]),[fileName,setFileName]=useState(''),[loading,setLoading]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState('');
 const [budget,setBudget]=useState(''),[budgetPlan,setBudgetPlan]=useState(null);
 async function refresh(){try{setOrders(await api.listOrders()||[]);}catch(e){setError(e.message);}} useEffect(()=>{refresh();},[]);
 async function openOrder(id){setLoading(true);setError('');setBudgetPlan(null);try{const detail=await api.getOrder(id);setSelected(detail);setBudget(detail?.order?.budget?String(detail.order.budget):'');}catch(e){setError(e.message);}finally{setLoading(false);}}
 async function readOffers(file){setFileName(file.name);setError('');const wb=XLSX.read(await file.arrayBuffer(),{type:'array'});const raw=XLSX.utils.sheet_to_json(wb.Sheets[wb.SheetNames[0]],{defval:''});setOffersPreview(raw.map(r=>({product_code:String(get(r,'product_code')||'').trim(),product_name:String(get(r,'product_name')||'').trim(),supplier_name:String(get(r,'supplier_name')||'').trim(),list_price:num(get(r,'list_price')),discount_percent:num(get(r,'discount_percent')),extra_discount_percent:num(get(r,'extra_discount_percent')),bonus_quantity:num(get(r,'bonus_quantity')),bonus_base_quantity:num(get(r,'bonus_base_quantity')),available_quantity:get(r,'available_quantity')===''?null:num(get(r,'available_quantity')),minimum_order_quantity:num(get(r,'minimum_order_quantity')),lead_time_days:num(get(r,'lead_time_days')),payment_type:String(get(r,'payment_type')||'').trim(),valid_until:String(get(r,'valid_until')||'').slice(0,10),is_available:true})));}
 async function importOffers(){if(!offersPreview.length)return;setLoading(true);try{await api.importOffers({file_name:fileName,rows:offersPreview});setOffersPreview([]);setFileName('');setMessage('تم استيراد عروض الموردين بنجاح.');}catch(e){setError(e.message);}finally{setLoading(false);}}
 async function saveItem(item){setLoading(true);try{await api.updateItem({order_id:selected.order.id,id:item.id,approved_quantity:item.approved_quantity});await openOrder(selected.order.id);setMessage('تم حفظ الكمية المعتمدة.');}catch(e){setError(e.message);}finally{setLoading(false);}}
 async function optimize(){setLoading(true);try{await api.optimizeSuppliers(selected.order.id);await openOrder(selected.order.id);setMessage('تم اختيار أفضل مورد متاح لكل صنف حسب التكلفة الصافية.');}catch(e){setError(e.message);}finally{setLoading(false);}}
 async function previewBudget(){if(!selected||num(budget)<=0)return setError('أدخل قيمة الميزانية المطلوبة أولًا.');setLoading(true);setError('');try{setBudgetPlan(await api.previewBudget(selected.order.id,num(budget)));setMessage('تم عمل معاينة ذكية بدون تغيير الطلبية. راجع تقليل الكميات والحذف المقترح ثم اعتمد الخطة.');}catch(e){setError(e.message);}finally{setLoading(false);}}
 async function applyBudget(){if(!budgetPlan||!window.confirm('تطبيق الخطة سيعدل الكميات المعتمدة فعليًا. متابعة؟'))return;setLoading(true);setError('');try{const plan=await api.applyBudget(selected.order.id,num(budget));setBudgetPlan(plan);await openOrder(selected.order.id);await refresh();setMessage('تم تطبيق خطة الميزانية: تقليل الكميات أولًا، والحذف فقط للأصناف الأقل أولوية عند الضرورة.');}catch(e){setError(e.message);}finally{setLoading(false);}}
 async function approve(){setLoading(true);try{await api.approveOrder(selected.order.id);await openOrder(selected.order.id);await refresh();setMessage('تم اعتماد الطلبية.');}catch(e){setError(e.message);}finally{setLoading(false);}}
 function updateLocal(id,key,value){setSelected(s=>({...s,items:s.items.map(x=>x.id===id?{...x,[key]:value}:x)}));}
 function exportAll(){if(!selected)return;downloadWorkbook({'الطلبية':selected.items.map(x=>({'كود الصنف':x.product_code,'اسم الصنف':x.product_name,'المورد':x.supplier_name||'','الكمية المطلوبة':x.requested_quantity,'الكمية المعتمدة':x.approved_quantity,'طلبات العملاء':x.customer_requests_count||0,'الأولوية':x.priority_score||0,'السعر الصافي':x.expected_unit_cost,'الإجمالي':Number(x.approved_quantity||0)*Number(x.expected_unit_cost||0)}))},`${selected.order.order_number}.xlsx`);}
 function exportBySupplier(){if(!selected)return;const groups={};selected.items.filter(x=>num(x.approved_quantity)>0).forEach(x=>{const k=x.supplier_name||'بدون مورد';(groups[k]??=[]).push({'كود الصنف':x.product_code,'اسم الصنف':x.product_name,'الكمية':x.approved_quantity,'سعر الوحدة المتوقع':x.expected_unit_cost,'الإجمالي':num(x.approved_quantity)*num(x.expected_unit_cost)});});downloadWorkbook(groups,`${selected.order.order_number}_حسب_المورد.xlsx`);}
 function downloadOfferTemplate(){downloadWorkbook({'عروض الموردين':[{'كود الصنف':'','اسم الصنف':'','اسم المورد':'','السعر قبل الخصم':0,'الخصم %':0,'خصم اضافي %':0,'كمية البونص':0,'كمية اساس البونص':0,'الكمية المتاحة':'','اقل كمية طلب':0,'مدة التوريد':0,'طريقة الدفع':'','ساري حتى':''}]},'قالب_عروض_الموردين.xlsx');}
 const totals=useMemo(()=>{const items=selected?.items||[];return{count:items.filter(x=>num(x.approved_quantity)>0).length,total:items.reduce((s,x)=>s+num(x.approved_quantity)*num(x.expected_unit_cost),0),suppliers:new Set(items.map(x=>x.supplier_name).filter(Boolean)).size,protected:items.filter(x=>num(x.customer_requests_count)>0).length};},[selected]);
 return <div dir="rtl" className="p-4 md:p-6 space-y-5">
  <div className="flex items-center gap-3"><div className="rounded-xl bg-teal-50 p-2.5"><ClipboardCheck className="h-6 w-6 text-teal-600"/></div><div><h1 className="text-2xl font-bold">إدارة واعتماد طلبيات المشتريات</h1><p className="text-sm text-slate-500 mt-1">تحسين المورد + ضبط الميزانية بتقليل الكميات أولًا وحماية طلبات العملاء قبل حذف أي صنف.</p></div></div>
  {error&&<div className="rounded-xl border border-red-200 bg-red-50 p-3 text-red-700 flex gap-2"><AlertTriangle className="w-5 h-5"/>{error}</div>}{message&&<div className="rounded-xl border border-teal-200 bg-teal-50 p-3 text-teal-700">{message}</div>}
  <section className="rounded-2xl border bg-white p-4 shadow-sm"><div className="flex flex-wrap items-center justify-between gap-2 mb-4"><h2 className="font-bold flex gap-2"><FileSpreadsheet className="w-5 h-5 text-teal-600"/>عروض الموردين</h2><button onClick={downloadOfferTemplate} className="rounded-lg border px-3 py-2 text-sm font-semibold">تنزيل قالب Excel</button></div><div className="flex flex-wrap gap-3 items-center"><input type="file" accept=".xlsx,.xls,.csv" onChange={e=>e.target.files?.[0]&&readOffers(e.target.files[0])}/>{offersPreview.length>0&&<button disabled={loading} onClick={importOffers} className="rounded-lg bg-teal-600 text-white px-4 py-2 font-semibold">استيراد {offersPreview.length} عرض</button>}</div></section>
  <div className="grid lg:grid-cols-[300px_1fr] gap-4"><aside className="rounded-2xl border bg-white p-3 shadow-sm h-fit"><h2 className="font-bold mb-3">الطلبيات</h2><div className="space-y-2 max-h-[650px] overflow-auto">{orders.map(o=><button key={o.id} onClick={()=>openOrder(o.id)} className="w-full text-right rounded-xl border p-3 hover:bg-teal-50"><div className="font-semibold">{o.order_number}</div><div className="text-xs text-slate-500 mt-1">{o.branch} • {o.status}</div><div className="text-sm font-bold mt-1">{money(o.approved_total)} ج</div></button>)}</div></aside>
   <main className="space-y-4">{selected&&<>
    <div className="grid sm:grid-cols-2 xl:grid-cols-4 gap-3">{[['أصناف فعالة',totals.count],['موردون',totals.suppliers],['أصناف محمية بطلب عميل',totals.protected],['إجمالي حالي',`${money(totals.total)} ج`]].map(([l,v])=><div key={l} className="rounded-2xl border bg-white p-4 shadow-sm"><div className="text-xs text-slate-500">{l}</div><div className="mt-2 text-xl font-bold">{v}</div></div>)}</div>
    <section className="rounded-2xl border-2 border-violet-200 bg-gradient-to-l from-violet-50 to-white p-4 shadow-sm"><div className="flex flex-col xl:flex-row xl:items-end gap-3"><div className="flex-1"><div className="flex items-center gap-2 font-black text-violet-900"><Sparkles className="w-5 h-5"/>مخ الميزانية الذكي</div><p className="mt-1 text-xs text-violet-700">لا يحذف الأصناف مباشرة: يقلل الكميات الزائدة أولًا، ثم يصل للحد الأدنى، والحذف آخر حل فقط. الأصناف المرتبطة بطلبات العملاء محمية.</p></div><label className="text-xs font-bold text-slate-600">قيمة الطلبية المستهدفة<input value={budget} onChange={e=>{setBudget(e.target.value);setBudgetPlan(null);}} type="number" className="mt-1 block w-52 rounded-xl border bg-white px-3 py-2 text-base font-black" placeholder="مثال 50000"/></label><button onClick={previewBudget} disabled={loading||selected.order.status==='معتمدة'} className="rounded-xl bg-violet-600 px-4 py-2.5 font-bold text-white">معاينة الضبط الذكي</button></div>
     {budgetPlan&&<div className="mt-4 space-y-3"><div className="grid grid-cols-2 md:grid-cols-6 gap-2">{[['قبل',money(budgetPlan.before_total)],['المستهدف',money(budgetPlan.target_budget)],['بعد الخطة',money(budgetPlan.after_total)],['التوفير',money(budgetPlan.savings)],['كميات تم تقليلها',budgetPlan.reduced_items],['أصناف حُذفت',budgetPlan.removed_items]].map(([l,v])=><div key={l} className="rounded-xl border bg-white p-3"><div className="text-[11px] text-slate-500">{l}</div><div className="mt-1 font-black">{v}{typeof v==='string'&&['قبل','المستهدف','بعد الخطة','التوفير'].includes(l)?' ج':''}</div></div>)}</div><div className={`rounded-xl p-3 text-sm font-bold ${budgetPlan.feasible?'bg-emerald-50 text-emerald-800':'bg-red-50 text-red-800'}`}>{budgetPlan.feasible?'الخطة داخل الميزانية مع الحفاظ على الحماية المطلوبة.':'الميزانية أقل من الحد الآمن للأصناف المرتبطة بطلبات العملاء؛ لن يتم كسر الحماية تلقائيًا.'}</div><div className="max-h-72 overflow-auto rounded-xl border bg-white"><table className="w-full min-w-[850px] text-xs"><thead className="sticky top-0 bg-slate-50"><tr>{['الصنف','الأولوية','طلب عميل','الكمية قبل','الكمية المقترحة','التوفير','القرار'].map(h=><th key={h} className="p-2 text-right">{h}</th>)}</tr></thead><tbody>{(budgetPlan.plan||[]).filter(p=>num(p.original_quantity)!==num(p.proposed_quantity)).map(p=><tr key={p.id} className="border-t"><td className="p-2 font-bold">{p.product_name}<div className="text-[10px] text-slate-400">{p.product_code}</div></td><td className="p-2">{p.priority_score}</td><td className="p-2">{p.protected?<span className="inline-flex gap-1 text-emerald-700"><ShieldCheck className="w-3.5 h-3.5"/>محمي ({p.customer_requests_count})</span>:'—'}</td><td className="p-2">{p.original_quantity}</td><td className="p-2 font-black">{p.proposed_quantity}</td><td className="p-2">{money(p.saved_amount)} ج</td><td className="p-2">{p.proposed_quantity===0?<span className="text-red-700 inline-flex gap-1"><Trash2 className="w-3.5 h-3.5"/>حذف أخير</span>:<span className="text-violet-700 inline-flex gap-1"><Scissors className="w-3.5 h-3.5"/>تقليل كمية</span>}<div className="mt-1 text-[10px] text-slate-500">{p.reason}</div></td></tr>)}</tbody></table></div>{budgetPlan.feasible&&<button onClick={applyBudget} disabled={loading} className="rounded-xl bg-emerald-600 px-5 py-2.5 font-black text-white">تطبيق الخطة على الطلبية</button>}</div>}
    </section>
    <div className="flex flex-wrap gap-2"><button onClick={optimize} disabled={loading||selected.order.status==='معتمدة'} className="rounded-lg bg-slate-800 text-white px-4 py-2 font-semibold flex gap-2"><Sparkles className="w-4 h-4"/>تحسين الموردين</button><button onClick={approve} disabled={loading||selected.order.status==='معتمدة'} className="rounded-lg bg-teal-600 text-white px-4 py-2 font-semibold flex gap-2"><CheckCircle2 className="w-4 h-4"/>اعتماد الطلبية</button><button onClick={exportAll} className="rounded-lg border bg-white px-4 py-2 font-semibold flex gap-2"><Download className="w-4 h-4"/>تصدير إجمالي</button><button onClick={exportBySupplier} className="rounded-lg border bg-white px-4 py-2 font-semibold flex gap-2"><Download className="w-4 h-4"/>حسب المورد</button></div>
    <div className="rounded-2xl border bg-white shadow-sm overflow-auto"><table className="min-w-[1050px] w-full text-sm"><thead className="bg-slate-50"><tr>{['الصنف','المطلوب','المعتمد','طلبات العملاء','الأولوية','المورد','سعر الوحدة','الإجمالي','حفظ كمية'].map(h=><th key={h} className="p-3 text-right">{h}</th>)}</tr></thead><tbody>{selected.items.map(x=><tr key={x.id} className={`border-t ${num(x.customer_requests_count)>0?'bg-emerald-50/40':''}`}><td className="p-3"><div className="font-semibold">{x.product_name}</div><div className="text-xs text-slate-400">{x.product_code}</div></td><td className="p-3">{x.requested_quantity}</td><td className="p-3"><input type="number" min="0" value={x.approved_quantity??0} onChange={e=>updateLocal(x.id,'approved_quantity',num(e.target.value))} className="w-24 rounded border p-2"/></td><td className="p-3 font-bold">{x.customer_requests_count||0}</td><td className="p-3">{x.priority_score||0}</td><td className="p-3">{x.supplier_name||'—'}</td><td className="p-3">{money(x.expected_unit_cost)}</td><td className="p-3 font-bold">{money(num(x.approved_quantity)*num(x.expected_unit_cost))}</td><td className="p-3"><button disabled={loading||selected.order.status==='معتمدة'} onClick={()=>saveItem(x)} className="rounded bg-slate-800 text-white p-2"><Save className="w-4 h-4"/></button></td></tr>)}</tbody></table></div>
   </>}</main></div>
 </div>;
}
