import {useEffect,useMemo,useState} from 'react';
import {treasuryApi} from '@/api/treasuryApi';
import {RefreshCw,WalletCards,ArrowDownCircle,ArrowUpCircle,Send,CheckCircle2,AlertTriangle} from 'lucide-react';
const money=v=>new Intl.NumberFormat('ar-EG',{maximumFractionDigits:2}).format(Number(v||0));
const today=()=>new Date().toISOString().slice(0,10);
export default function TreasuryCenter(){
 const [data,setData]=useState({treasuries:[],transactions:[],transfers:[]});const [loading,setLoading]=useState(false);const [error,setError]=useState('');const [message,setMessage]=useState('');
 const [movement,setMovement]=useState({branch:'دواء الشامي',transaction_date:today(),direction:'debit',category:'salary',amount:'',description:'',counterparty:''});
 const [transfer,setTransfer]=useState({branch:'دواء الشامي',transaction_date:today(),transfer_type:'instapay',amount:'',notes:''});
 async function refresh(){setLoading(true);setError('');try{setData(await treasuryApi.dashboard()||{treasuries:[],transactions:[],transfers:[]});}catch(e){setError(e.message);}finally{setLoading(false);}}
 useEffect(()=>{refresh();},[]);
 async function run(fn,success){setLoading(true);setError('');try{await fn();setMessage(success);await refresh();}catch(e){setError(e.message);}finally{setLoading(false);}}
 const cycle=useMemo(()=>{const d=new Date(),day=d.getDate();const end=new Date(d.getFullYear(),d.getMonth()+(day>=26?1:0),25);const start=new Date(d.getFullYear(),d.getMonth()-(day<26?1:0),26);return `${start.toLocaleDateString('ar-EG')} — ${end.toLocaleDateString('ar-EG')}`;},[]);
 return <div dir="rtl" className="p-4 md:p-6 space-y-5">
  <div><h1 className="text-2xl font-bold">الخزنة والعهد والتحويلات</h1><p className="text-sm text-slate-500 mt-1">دورة المبيعات الحالية: {cycle} — صافي الشيفتات، التحويلات، المدفوعات والحركات اليدوية.</p></div>
  {error&&<div className="rounded-xl border border-red-200 bg-red-50 p-3 text-red-700 flex gap-2"><AlertTriangle className="w-5 h-5"/>{error}</div>}{message&&<div className="rounded-xl border border-emerald-200 bg-emerald-50 p-3 text-emerald-700">{message}</div>}
  <div className="flex flex-wrap gap-2"><button disabled={loading} onClick={()=>run(()=>treasuryApi.syncShifts(),'تم ترحيل صافي الشيفتات الجديدة للخزنة بدون تكرار.')} className="rounded-lg bg-teal-600 text-white px-4 py-2 font-semibold">ترحيل صافي الشيفتات</button><button onClick={refresh} className="rounded-lg border bg-white px-4 py-2 flex gap-2"><RefreshCw className="w-4 h-4"/>تحديث</button></div>
  <div className="grid sm:grid-cols-2 gap-4">{data.treasuries.map(t=><div key={t.id} className="rounded-2xl border bg-white p-5 shadow-sm"><div className="flex items-center justify-between"><div><div className="text-sm text-slate-500">خزنة {t.branch}</div><div className="text-3xl font-bold mt-2">{money(t.balance)} ج</div></div><WalletCards className="w-10 h-10 text-teal-600"/></div><div className="text-xs text-slate-400 mt-3">الرصيد الافتتاحي: {money(t.opening_balance)} ج</div></div>)}</div>
  <div className="grid lg:grid-cols-2 gap-4">
   <section className="rounded-2xl border bg-white p-4 shadow-sm"><h2 className="font-bold mb-3">حركة مالية يدوية</h2><div className="grid sm:grid-cols-2 gap-2">{[['branch','الفرع'],['transaction_date','التاريخ'],['amount','القيمة'],['counterparty','الطرف']].map(([k,l])=><label key={k} className="text-sm">{l}{k==='branch'?<select value={movement[k]} onChange={e=>setMovement({...movement,[k]:e.target.value})} className="mt-1 w-full border rounded-lg p-2"><option>دواء الشامي</option><option>دواء شكري</option></select>:<input type={k==='transaction_date'?'date':k==='amount'?'number':'text'} value={movement[k]} onChange={e=>setMovement({...movement,[k]:e.target.value})} className="mt-1 w-full border rounded-lg p-2"/>}</label>)}<label className="text-sm">النوع<select value={movement.direction} onChange={e=>setMovement({...movement,direction:e.target.value})} className="mt-1 w-full border rounded-lg p-2"><option value="debit">خصم من الخزنة</option><option value="credit">إضافة للخزنة</option></select></label><label className="text-sm">التصنيف<select value={movement.category} onChange={e=>setMovement({...movement,category:e.target.value})} className="mt-1 w-full border rounded-lg p-2"><option value="salary">مرتبات</option><option value="rent">إيجار</option><option value="supplier_payment">دفعة مورد</option><option value="manual_income">إضافة يدوية</option><option value="other_expense">مصروف آخر</option></select></label></div><textarea value={movement.description} onChange={e=>setMovement({...movement,description:e.target.value})} placeholder="البيان" className="mt-2 w-full border rounded-lg p-2"/><button disabled={loading||!movement.amount} onClick={()=>run(()=>treasuryApi.manualTransaction({...movement,amount:Number(movement.amount)}),'تم تسجيل الحركة في الخزنة.')} className="mt-3 rounded-lg bg-slate-800 text-white px-4 py-2 font-semibold">تسجيل الحركة</button></section>
   <section className="rounded-2xl border bg-white p-4 shadow-sm"><h2 className="font-bold mb-3">إنستا باي / فودافون كاش / تحويل زكريا</h2><div className="grid sm:grid-cols-2 gap-2"><label className="text-sm">الفرع<select value={transfer.branch} onChange={e=>setTransfer({...transfer,branch:e.target.value})} className="mt-1 w-full border rounded-lg p-2"><option>دواء الشامي</option><option>دواء شكري</option></select></label><label className="text-sm">النوع<select value={transfer.transfer_type} onChange={e=>setTransfer({...transfer,transfer_type:e.target.value})} className="mt-1 w-full border rounded-lg p-2"><option value="instapay">إنستا باي</option><option value="vodafone_cash">فودافون كاش</option><option value="zakaria_internal">تحويل داخلي لفرع زكريا</option><option value="other">أخرى</option></select></label><label className="text-sm">التاريخ<input type="date" value={transfer.transaction_date} onChange={e=>setTransfer({...transfer,transaction_date:e.target.value})} className="mt-1 w-full border rounded-lg p-2"/></label><label className="text-sm">القيمة<input type="number" value={transfer.amount} onChange={e=>setTransfer({...transfer,amount:e.target.value})} className="mt-1 w-full border rounded-lg p-2"/></label></div><textarea value={transfer.notes} onChange={e=>setTransfer({...transfer,notes:e.target.value})} placeholder="ملاحظات أو رقم التحويل" className="mt-2 w-full border rounded-lg p-2"/><button disabled={loading||!transfer.amount} onClick={()=>run(()=>treasuryApi.createTransfer({...transfer,amount:Number(transfer.amount)}),'تم تسجيل التحويل كعهدة معلقة.')} className="mt-3 rounded-lg bg-violet-600 text-white px-4 py-2 font-semibold">تسجيل تحويل جديد</button></section>
  </div>
  <section className="rounded-2xl border bg-white shadow-sm overflow-auto"><div className="p-4 font-bold">التحويلات والعهد</div><table className="min-w-[1000px] w-full text-sm"><thead className="bg-slate-50"><tr>{['التاريخ','الفرع','النوع','القيمة','الحالة','منشئ التحويل','الإجراء'].map(h=><th key={h} className="p-3 text-right">{h}</th>)}</tr></thead><tbody>{data.transfers.map(x=><tr key={x.id} className="border-t"><td className="p-3">{x.transaction_date}</td><td className="p-3">{x.branch}</td><td className="p-3">{x.transfer_type}</td><td className="p-3 font-bold">{money(x.amount)} ج</td><td className="p-3">{x.status==='pending'?'في عهدة الدكتور':x.status==='transferred_to_accounts'?'تم التحويل لمدير الحسابات':x.status==='posted_to_treasury'?'تم التسجيل بالخزنة':x.status}</td><td className="p-3">{x.created_by_name||'—'}</td><td className="p-3">{x.status==='pending'&&<button onClick={()=>run(()=>treasuryApi.handoverTransfer(x.id),'تم تحويل العهدة لمدير الحسابات.')} className="rounded bg-violet-600 text-white px-3 py-1.5 flex gap-1"><Send className="w-4 h-4"/>تم التحويل للحسابات</button>}{x.status==='transferred_to_accounts'&&<button onClick={()=>run(()=>treasuryApi.postTransfer(x.id),'تم تسجيل المبلغ في خزنة الفرع.')} className="rounded bg-emerald-600 text-white px-3 py-1.5 flex gap-1"><CheckCircle2 className="w-4 h-4"/>تم التسجيل بالخزنة</button>}</td></tr>)}</tbody></table></section>
  <section className="rounded-2xl border bg-white shadow-sm overflow-auto"><div className="p-4 font-bold">آخر حركات الخزنة</div><table className="min-w-[900px] w-full text-sm"><thead className="bg-slate-50"><tr>{['التاريخ','الفرع','الحركة','التصنيف','القيمة','البيان'].map(h=><th key={h} className="p-3 text-right">{h}</th>)}</tr></thead><tbody>{data.transactions.map(x=><tr key={x.id} className="border-t"><td className="p-3">{x.transaction_date}</td><td className="p-3">{x.branch}</td><td className="p-3">{x.direction==='credit'?<span className="text-emerald-700 flex gap-1"><ArrowDownCircle className="w-4 h-4"/>إضافة</span>:<span className="text-red-700 flex gap-1"><ArrowUpCircle className="w-4 h-4"/>خصم</span>}</td><td className="p-3">{x.category}</td><td className="p-3 font-bold">{money(x.amount)} ج</td><td className="p-3">{x.description||'—'}</td></tr>)}</tbody></table></section>
 </div>
}